# Generated by Django 5.1.1 on 2024-09-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('linkedin_link', models.URLField(verbose_name='LinkedIn Link')),
                ('company_type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('employee_count', models.IntegerField()),
                ('year_founded', models.IntegerField()),
                ('investment_stage', models.CharField(max_length=50)),
                ('funding', models.IntegerField()),
            ],
        ),
    ]
