# Generated by Django 5.1.1 on 2024-11-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='LinkedIn Link')),
                ('linkedin_sales_link', models.URLField(unique=True, verbose_name='LinkedIn Sales Navigator Link')),
                ('company_type', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=100)),
                ('specialties', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('year_founded', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=150, null=True)),
                ('investment_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('funding', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
