# Generated by Django 5.1.1 on 2024-11-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_headquarters_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
