# Generated by Django 5.1.1 on 2024-11-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_employee_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
