# Generated by Django 5.1.1 on 2024-11-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='specialties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
