# Generated by Django 5.1.1 on 2024-09-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='possition',
            new_name='position',
        ),
    ]
