# Generated by Django 5.1.1 on 2024-11-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_comments',
            field=models.FileField(blank=True, null=True, upload_to='linkedin_comments/'),
        ),
    ]
