services:
  web:
    build: . # Build from the Dockerfile located in linkedin_network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app # Mount the local project folder into the container
    ports:
      - "80:8000" # Expose port 8000 to access the Django app in a browser
    env_file:
      - .env.prod # Load environment variables from the .env.dev file
    depends_on:
      - db # Ensure the database starts before the web service

  db:
    image: postgres:13 # Use PostgreSQL as the database
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
volumes:
  postgres_data:
