# Generated by Django 5.1.1 on 2024-11-13 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_on', models.DateTimeField()),
                ('connection', models.ForeignKey(db_column='connection_url', on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to='connections.connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'connection')},
            },
        ),
        migrations.AddField(
            model_name='connection',
            name='connections',
            field=models.ManyToManyField(related_name='connections', through='connections.UserConnection', to=settings.AUTH_USER_MODEL),
        ),
    ]
