# Generated by Django 5.1.1 on 2024-09-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('current_company', models.CharField(max_length=100)),
                ('current_position', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
            ],
        ),
    ]
