# Generated by Django 5.1.1 on 2024-09-28 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_headquarters_alter_company_description_and_more'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
