# Generated by Django 5.1.1 on 2024-11-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
