# Generated by Django 5.1.1 on 2024-09-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_current_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='current_location',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='connection',
            name='current_position',
        ),
    ]
