# Generated by Django 5.1.1 on 2024-11-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_connection_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_strength',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
