# Generated by Django 5.1.1 on 2024-09-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_rename_current_location_connection_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
