# Generated by Django 5.1.1 on 2024-11-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0005_userconnection_connection_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
