# Generated by Django 5.1.1 on 2024-11-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0006_alter_connection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='connected_on',
            field=models.DateTimeField(),
        ),
    ]
