# Generated by Django 5.1.1 on 2024-09-29 16:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_role_end_date_alter_role_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='location',
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
