# Generated by Django 5.1.1 on 2024-11-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection_connection_strength'),
        ('roles', '0003_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='connections.connection'),
        ),
    ]
